# Generated by Django 4.1.7 on 2023-09-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='travel_images/')),
                ('tour_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
